[platformio]
default_envs = cyd_esp32_2432s028
src_dir = .
extra_configs =
  ../firmware_common/platformio_pioarduino.ini

[env:cyd_esp32_2432s028]
board = esp32dev
lib_ldf_mode = deep+
lib_extra_dirs = ../lib
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bodmer/TFT_eSPI
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  sparkfun/SX1509 IO Expander @ ^3.0.6
  mikalhart/TinyGPSPlus
  adafruit/Adafruit ADS1X15
build_flags =
  -I ../wall_e_audio
build_src_filter =
  +<*.ino>
  +<*.cpp>
