[platformio]
default_envs = cyd_esp32_2432s028
src_dir = .
lib_extra_dirs = ../lib
extra_configs =
  ../firmware_common/platformio_pioarduino.ini

[env:cyd_esp32_2432s028]
board = esp32dev
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen
  sparkfun/SparkFun SX1509 IO Expander
  mikalhart/TinyGPSPlus
  adafruit/Adafruit ADS1X15
build_flags =
  -I ../wall_e_audio
build_src_filter =
  +<*.ino>
  +<*.cpp>
  -<walle_emotion_pose.cpp>
