[platformio]
default_envs = cyd_esp32_2432s028

[env:cyd_esp32_2432s028]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen
  sparkfun/SparkFun SX1509 IO Expander
  mikalhart/TinyGPSPlus
  adafruit/Adafruit ADS1X15
build_src_filter =
  +<*.ino>
  +<*.cpp>
