[platformio]
default_envs = wall_e_audio_s3

[env:wall_e_audio_s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_deps =
	DFRobot/DFRobotDFPlayerMini
