/**
 * Showduino monorepo firmware version (shared across PlatformIO modules).
 * Bump MAJOR/MINOR/PATCH here for releases; BUILD + GIT_HASH come from
 * showduino_version_build.h (generated by scripts/gen_showduino_version.sh).
 */
#pragma once

#include <Arduino.h>

#define SHOWDUINO_VERSION_MAJOR 0
#define SHOWDUINO_VERSION_MINOR 2
#define SHOWDUINO_VERSION_PATCH 0

#include "showduino_version_build.h"

#ifndef SHOWDUINO_BUILD
#define SHOWDUINO_BUILD 0
#endif

#ifndef SHOWDUINO_GIT_HASH
#define SHOWDUINO_GIT_HASH "unknown"
#endif

/** Log unified firmware identity at boot (after Serial.begin). */
#define SHOWDUINO_LOG_BOOT_VERSION(module_tag)                                      \
  do {                                                                              \
    Serial.printf(                                                                  \
        "[Showduino] %s firmware %u.%u.%u build %u (%s)\n",                        \
        (module_tag),                                                               \
        (unsigned)SHOWDUINO_VERSION_MAJOR,                                        \
        (unsigned)SHOWDUINO_VERSION_MINOR,                                        \
        (unsigned)SHOWDUINO_VERSION_PATCH,                                        \
        (unsigned)SHOWDUINO_BUILD,                                                  \
        SHOWDUINO_GIT_HASH);                                                        \
  } while (0)
