#!/usr/bin/env bash
# Emit firmware_common/include/showduino_version_build.h (BUILD + GIT_HASH).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/firmware_common/include/showduino_version_build.h"

BUILD="${SHOWDUINO_BUILD:-${GITHUB_RUN_NUMBER:-0}}"
GIT_HASH="${SHOWDUINO_GIT_HASH:-$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)}"

cat >"$OUT" <<EOF
#pragma once
/* Generated by scripts/gen_showduino_version.sh — do not edit. */
#define SHOWDUINO_BUILD ${BUILD}u
#define SHOWDUINO_GIT_HASH "${GIT_HASH}"
EOF

echo "Wrote $OUT (build=${BUILD}, git=${GIT_HASH})"
