[platformio]
default_envs = wall_e_brain_s3

[env:wall_e_brain_s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  adafruit/Adafruit PWM Servo Driver Library
  mikalhart/TinyGPSPlus
  jrowberg/I2Cdevlib-MPU6050
build_src_filter =
  +<main.ino>
  +<espnow_receiver.cpp>
  +<main/*.cpp>
  -<main/main.ino>
  -<main/espnow_receiver.cpp>
